### ISSUE TITLE
kobopatch.yaml overrides with user-provided strings

### ISSUE THREAD

**Issue by da-moo** [geek1011/kobopatch#18]
Hi there! Thanks for making the kobopatch system, it's very useful. When converting my existing set of enabled patches to the override yaml file, I noticed I'm not able (or I just don't know the correct way) to include customizable user strings for patches that use them, so I can just have one master override file rather than edit the individual patch file to include my strings. 

Example `kobopatch.yaml` with the monospace font patch:

```yml
overrides:
  src/librmsdk.so.1.0.0.yaml:
    Default ePub monospace font (Courier):
      - Enabled: yes
      - FindReplaceString: { Find: 'CourierStd.otf', Replace: 'normal/Hack' }
      - FindReplaceString: { Find: 'CourierStd-Bold.otf', Replace: 'bold/Hack' }
      - FindReplaceString: { Find: 'CourierStd-Oblique.otf', Replace: 'italic/Hack' }
      - FindReplaceString: { Find: 'CourierStd-BoldOblique.otf', Replace: 'bolditalic/Hack' }
```

When running to the tool I get the following error:

```log
kobopatch v0.10.4
https://github.com/geek1011/kobopatch

Loading configuration from kobopatch.yaml
Error: could not load config file: error reading kobopatch.yaml: yaml: unmarshal errors:
  line 42: cannot unmarshal !!seq into bool
```

If this isn't supported behavior, please consider this a feature request!
