### ISSUE TITLE
Add more symbol resolution options

### ISSUE THREAD

**Issue by geek1011** [geek1011/kobopatch#32]
I'm planning on adding better symbol resolution stuff based on my work from today: https://gist.github.com/geek1011/167a87c3a0360366084a2e8e0cf95b83.

This will be done along with #31, and will deprecate #21. I will also be rewriting the BLX encoding to be more efficient and also support the B winstruction

The following new instructions/options will be added/changed:
- *ReplaceBytes* / *ReplaceBytesAtSymbol*
  - FindInstBLX (arg is one of Offset/SymPLT/SymPLTTail/Sym)
  - FindInstB (arg is one of Offset/SymPLT/SymPLTTail/Sym)
  - ReplaceInstBLX (arg is one of Offset/SymPLT/SymPLTTail/Sym)
  - ReplaceInstB (arg is one of Offset/SymPLT/SymPLTTail/Sym)
- FindBaseAddressSym (arg is one of Offset/SymPLT/SymPLTTail/Sym)
  - Can also specify an additional offset.

Note: The args will be able to be specified as either an offset directly, or an object with one of the following string properties: SymPLT/SymPLTTail/Sym.

The following instructions/options will be deprecated:
- ReplaceBytes / ReplaceBytesAtSymbol
  - FindBLX
- FindBaseAddressSymbol (as part of #31)
- ReplaceBLX (in favour of the FindInstBLX and ReplaceInstBLX options of ReplaceBytes)

Advantages:
- Most of the current version-dependent patches will likely become multi-version (or almost multi-version).
- No more segfaults from address typos.
- Significantly easier patch updates.
- Simpler code.

Disadvantages:
- Another ~500 lines of code.
- Adding an ARM disassembly lib for parsing the PLT (rsc.io/arm).
  - Slightly larger kobopatch binary size.
- Needing to emulate a subset of ARM instructions during patching (mov, ldr) for parsing the PLT.
  - Note that I've already tested the code against most versions of libnickel, including old ones.
  - Note that incorrect emulation will be automatically detected, as the bytes won't match for the FindInstBLX and FindInstB instructions.

**Comment by geek1011** [comment]
Some real usage examples:

**Before:**
```yaml
Change Browse Kobo home screen link target - Activity:
  - Enabled: no
  - PatchGroup: Browse Kobo link target
  - Description: See the comment above.
  - ReplaceBytes: {Offset: 0x9D5262, FindH: E8 F6 FD B4, ReplaceH: DE F6 69 B7} # tail call to bx before ReadingLifeNavMixin::chooseActivity (sub_493e3c)
  - ReplaceBLX:   {Offset: 0x9D4C22, Find:  0x4CFCB0,    Replace:  0x4C307C}    # N3DeviceCharm::extrasName (Activity)
```

**After:**
```yaml
Change Browse Kobo home screen link target - Activity:
  - Enabled: no
  - PatchGroup: Browse Kobo link target
  - Description: See the comment above.
  - ReplaceBytesAtSymbol:
      Sym:    {Sym: "BrowseKoboWidget::tapped()"}
      Offset: 14
      FindInstB:    {SymPLTTail: "DiscoverNavMixin::storefront()"}
      ReplaceInstB: {SymPLTTail: "ReadingLifeNavMixin::chooseActivity()"}
  - ReplaceBytesAtSymbol:
      Sym:    {Sym: "BrowseKoboWidget::BrowseKoboWidget(QWidget*)"}
      Offset: 190
      FindInstBLX:    {SymPLT: "N3DeviceCharm::shopName()"}
      ReplaceInstBLX: {SymPLT: "N3DeviceCharm::extrasName()"}
```

**Comment by geek1011** [comment]
Some examples (I've slightly revised the instructions):

**Before:**
```yaml
Remove PDF map widget shown during panning:
  - Enabled: no
  - Description: Removes the PDF map widget shown during panning and zooming.
  # In the function which shows the widget, replace all tail calls to anything
  # with the bx pc before N3AdobeReader::hideMapWidget@PLT.
  - ReplaceBytesAtSymbol: {Symbol: "N3AdobeReader::showMapWidget()", Offset:  79, FindH: E9 F7 26 BD, ReplaceH: E8 F7 62 BF} # b.w sub_17e40
  - ReplaceBytesAtSymbol: {Symbol: "N3AdobeReader::showMapWidget()", Offset: 189, FindH: E9 F7 EF BC, ReplaceH: E8 F7 2B BF} # b.w sub_17e40
```

**After (multi-version):**
```yaml
Remove PDF map widget shown during panning:
  - Enabled: no
  - Description: Removes the PDF map widget shown during panning and zooming.
  - BaseAddress:  {Sym: "N3AdobeReader::showMapWidget()"}
  - ReplaceBytes: {Offset:  80, FindInstBW: {SymPLTTail: "N3AdobeReader::updatePanningMap()"}, ReplaceInstBW: {SymPLTTail: "N3AdobeReader::hideMapWidget()"}}
  - ReplaceBytes: {Offset: 190, FindInstBW: {SymPLTTail: "N3AdobeReader::updatePanningMap()"}, ReplaceInstBW: {SymPLTTail: "N3AdobeReader::hideMapWidget()"}}
```
